package org.bodytrack.client;

import java.util.HashMap;
import java.util.Map;

import com.google.gwt.core.client.GWT;
import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.i18n.client.TimeZone;
import com.google.gwt.i18n.client.constants.TimeZoneConstants;

public class TimeZoneSegment extends JavaScriptObject {

	protected TimeZoneSegment(){}

	public final native String getTimeZoneName() /*-{
		return this.name;
	}-*/;

	public final native double getOffset() /*-{
		return this.offset / 1000.0;
	}-*/;

	public final native boolean usesDST() /*-{
		return this.usesDST;
	}-*/;

	public final native double getStart() /*-{
		return this.start / 1000.0;
	}-*/;

	public final native double getEnd() /*-{
		return this.end / 1000.0;
	}-*/;

	private static Map<String,TimeZone> tzMapping;


	public final TimeZone getTimeZone() {
		updateTZMapping();
		return tzMapping.get(getTimeZoneName());
	}


	private static void updateTZMapping() {
		if (tzMapping != null)
			return;
		final TimeZoneConstants timeZoneConstants = GWT.create(TimeZoneConstants.class);
		tzMapping = new HashMap<String,TimeZone>();
		addTZToMap(tzMapping, timeZoneConstants.africaAbidjan());
		addTZToMap(tzMapping, timeZoneConstants.africaAccra());
		addTZToMap(tzMapping, timeZoneConstants.africaAddisAbaba());
		addTZToMap(tzMapping, timeZoneConstants.africaAlgiers());
		addTZToMap(tzMapping, timeZoneConstants.africaAsmera());
		addTZToMap(tzMapping, timeZoneConstants.africaBamako());
		addTZToMap(tzMapping, timeZoneConstants.africaBangui());
		addTZToMap(tzMapping, timeZoneConstants.africaBanjul());
		addTZToMap(tzMapping, timeZoneConstants.africaBissau());
		addTZToMap(tzMapping, timeZoneConstants.africaBlantyre());
		addTZToMap(tzMapping, timeZoneConstants.africaBrazzaville());
		addTZToMap(tzMapping, timeZoneConstants.africaBujumbura());
		addTZToMap(tzMapping, timeZoneConstants.africaCairo());
		addTZToMap(tzMapping, timeZoneConstants.africaCasablanca());
		addTZToMap(tzMapping, timeZoneConstants.africaCeuta());
		addTZToMap(tzMapping, timeZoneConstants.africaConakry());
		addTZToMap(tzMapping, timeZoneConstants.africaDakar());
		addTZToMap(tzMapping, timeZoneConstants.africaDaresSalaam());
		addTZToMap(tzMapping, timeZoneConstants.africaDjibouti());
		addTZToMap(tzMapping, timeZoneConstants.africaDouala());
		addTZToMap(tzMapping, timeZoneConstants.africaElAaiun());
		addTZToMap(tzMapping, timeZoneConstants.africaFreetown());
		addTZToMap(tzMapping, timeZoneConstants.africaGaborone());
		addTZToMap(tzMapping, timeZoneConstants.africaHarare());
		addTZToMap(tzMapping, timeZoneConstants.africaJohannesburg());
		addTZToMap(tzMapping, timeZoneConstants.africaKampala());
		addTZToMap(tzMapping, timeZoneConstants.africaKhartoum());
		addTZToMap(tzMapping, timeZoneConstants.africaKigali());
		addTZToMap(tzMapping, timeZoneConstants.africaKinshasa());
		addTZToMap(tzMapping, timeZoneConstants.africaLagos());
		addTZToMap(tzMapping, timeZoneConstants.africaLibreville());
		addTZToMap(tzMapping, timeZoneConstants.africaLome());
		addTZToMap(tzMapping, timeZoneConstants.africaLuanda());
		addTZToMap(tzMapping, timeZoneConstants.africaLubumbashi());
		addTZToMap(tzMapping, timeZoneConstants.africaLusaka());
		addTZToMap(tzMapping, timeZoneConstants.africaMalabo());
		addTZToMap(tzMapping, timeZoneConstants.africaMaputo());
		addTZToMap(tzMapping, timeZoneConstants.africaMaseru());
		addTZToMap(tzMapping, timeZoneConstants.africaMbabane());
		addTZToMap(tzMapping, timeZoneConstants.africaMogadishu());
		addTZToMap(tzMapping, timeZoneConstants.africaMonrovia());
		addTZToMap(tzMapping, timeZoneConstants.africaNairobi());
		addTZToMap(tzMapping, timeZoneConstants.africaNdjamena());
		addTZToMap(tzMapping, timeZoneConstants.africaNiamey());
		addTZToMap(tzMapping, timeZoneConstants.africaNouakchott());
		addTZToMap(tzMapping, timeZoneConstants.africaOuagadougou());
		addTZToMap(tzMapping, timeZoneConstants.africaPortoNovo());
		addTZToMap(tzMapping, timeZoneConstants.africaSaoTome());
		addTZToMap(tzMapping, timeZoneConstants.africaTripoli());
		addTZToMap(tzMapping, timeZoneConstants.africaTunis());
		addTZToMap(tzMapping, timeZoneConstants.africaWindhoek());
		addTZToMap(tzMapping, timeZoneConstants.americaAdak());
		addTZToMap(tzMapping, timeZoneConstants.americaAnchorage());
		addTZToMap(tzMapping, timeZoneConstants.americaAnguilla());
		addTZToMap(tzMapping, timeZoneConstants.americaAntigua());
		addTZToMap(tzMapping, timeZoneConstants.americaAraguaina());
		addTZToMap(tzMapping, timeZoneConstants.americaArgentinaLaRioja());
		addTZToMap(tzMapping, timeZoneConstants.americaArgentinaRioGallegos());
		addTZToMap(tzMapping, timeZoneConstants.americaArgentinaSanJuan());
		addTZToMap(tzMapping, timeZoneConstants.americaArgentinaTucuman());
		addTZToMap(tzMapping, timeZoneConstants.americaArgentinaUshuaia());
		addTZToMap(tzMapping, timeZoneConstants.americaAruba());
		addTZToMap(tzMapping, timeZoneConstants.americaAsuncion());
		addTZToMap(tzMapping, timeZoneConstants.americaBahia());
		addTZToMap(tzMapping, timeZoneConstants.americaBarbados());
		addTZToMap(tzMapping, timeZoneConstants.americaBelem());
		addTZToMap(tzMapping, timeZoneConstants.americaBelize());
		addTZToMap(tzMapping, timeZoneConstants.americaBlancSablon());
		addTZToMap(tzMapping, timeZoneConstants.americaBoaVista());
		addTZToMap(tzMapping, timeZoneConstants.americaBogota());
		addTZToMap(tzMapping, timeZoneConstants.americaBoise());
		addTZToMap(tzMapping, timeZoneConstants.americaBuenosAires());
		addTZToMap(tzMapping, timeZoneConstants.americaCambridgeBay());
		addTZToMap(tzMapping, timeZoneConstants.americaCampoGrande());
		addTZToMap(tzMapping, timeZoneConstants.americaCancun());
		addTZToMap(tzMapping, timeZoneConstants.americaCaracas());
		addTZToMap(tzMapping, timeZoneConstants.americaCatamarca());
		addTZToMap(tzMapping, timeZoneConstants.americaCayenne());
		addTZToMap(tzMapping, timeZoneConstants.americaCayman());
		addTZToMap(tzMapping, timeZoneConstants.americaChicago());
		addTZToMap(tzMapping, timeZoneConstants.americaChihuahua());
		addTZToMap(tzMapping, timeZoneConstants.americaCoralHarbour());
		addTZToMap(tzMapping, timeZoneConstants.americaCordoba());
		addTZToMap(tzMapping, timeZoneConstants.americaCostaRica());
		addTZToMap(tzMapping, timeZoneConstants.americaCuiaba());
		addTZToMap(tzMapping, timeZoneConstants.americaCuracao());
		addTZToMap(tzMapping, timeZoneConstants.americaDanmarkshavn());
		addTZToMap(tzMapping, timeZoneConstants.americaDawson());
		addTZToMap(tzMapping, timeZoneConstants.americaDawsonCreek());
		addTZToMap(tzMapping, timeZoneConstants.americaDenver());
		addTZToMap(tzMapping, timeZoneConstants.americaDetroit());
		addTZToMap(tzMapping, timeZoneConstants.americaDominica());
		addTZToMap(tzMapping, timeZoneConstants.americaEdmonton());
		addTZToMap(tzMapping, timeZoneConstants.americaEirunepe());
		addTZToMap(tzMapping, timeZoneConstants.americaElSalvador());
		addTZToMap(tzMapping, timeZoneConstants.americaFortaleza());
		addTZToMap(tzMapping, timeZoneConstants.americaGlaceBay());
		addTZToMap(tzMapping, timeZoneConstants.americaGodthab());
		addTZToMap(tzMapping, timeZoneConstants.americaGooseBay());
		addTZToMap(tzMapping, timeZoneConstants.americaGrandTurk());
		addTZToMap(tzMapping, timeZoneConstants.americaGrenada());
		addTZToMap(tzMapping, timeZoneConstants.americaGuadeloupe());
		addTZToMap(tzMapping, timeZoneConstants.americaGuatemala());
		addTZToMap(tzMapping, timeZoneConstants.americaGuayaquil());
		addTZToMap(tzMapping, timeZoneConstants.americaGuyana());
		addTZToMap(tzMapping, timeZoneConstants.americaHalifax());
		addTZToMap(tzMapping, timeZoneConstants.americaHavana());
		addTZToMap(tzMapping, timeZoneConstants.americaHermosillo());
		addTZToMap(tzMapping, timeZoneConstants.americaIndianaKnox());
		addTZToMap(tzMapping, timeZoneConstants.americaIndianaMarengo());
		addTZToMap(tzMapping, timeZoneConstants.americaIndianaPetersburg());
		addTZToMap(tzMapping, timeZoneConstants.americaIndianapolis());
		addTZToMap(tzMapping, timeZoneConstants.americaIndianaVevay());
		addTZToMap(tzMapping, timeZoneConstants.americaIndianaVincennes());
		addTZToMap(tzMapping, timeZoneConstants.americaInuvik());
		addTZToMap(tzMapping, timeZoneConstants.americaIqaluit());
		addTZToMap(tzMapping, timeZoneConstants.americaJamaica());
		addTZToMap(tzMapping, timeZoneConstants.americaJujuy());
		addTZToMap(tzMapping, timeZoneConstants.americaJuneau());
		addTZToMap(tzMapping, timeZoneConstants.americaKentuckyMonticello());
		addTZToMap(tzMapping, timeZoneConstants.americaLaPaz());
		addTZToMap(tzMapping, timeZoneConstants.americaLima());
		addTZToMap(tzMapping, timeZoneConstants.americaLosAngeles());
		addTZToMap(tzMapping, timeZoneConstants.americaLouisville());
		addTZToMap(tzMapping, timeZoneConstants.americaMaceio());
		addTZToMap(tzMapping, timeZoneConstants.americaManagua());
		addTZToMap(tzMapping, timeZoneConstants.americaManaus());
		addTZToMap(tzMapping, timeZoneConstants.americaMartinique());
		addTZToMap(tzMapping, timeZoneConstants.americaMazatlan());
		addTZToMap(tzMapping, timeZoneConstants.americaMendoza());
		addTZToMap(tzMapping, timeZoneConstants.americaMenominee());
		addTZToMap(tzMapping, timeZoneConstants.americaMerida());
		addTZToMap(tzMapping, timeZoneConstants.americaMexicoCity());
		addTZToMap(tzMapping, timeZoneConstants.americaMiquelon());
		addTZToMap(tzMapping, timeZoneConstants.americaMoncton());
		addTZToMap(tzMapping, timeZoneConstants.americaMonterrey());
		addTZToMap(tzMapping, timeZoneConstants.americaMontevideo());
		addTZToMap(tzMapping, timeZoneConstants.americaMontreal());
		addTZToMap(tzMapping, timeZoneConstants.americaMontserrat());
		addTZToMap(tzMapping, timeZoneConstants.americaNassau());
		addTZToMap(tzMapping, timeZoneConstants.americaNewYork());
		addTZToMap(tzMapping, timeZoneConstants.americaNipigon());
		addTZToMap(tzMapping, timeZoneConstants.americaNome());
		addTZToMap(tzMapping, timeZoneConstants.americaNoronha());
		addTZToMap(tzMapping, timeZoneConstants.americaNorthDakotaCenter());
		addTZToMap(tzMapping, timeZoneConstants.americaNorthDakotaNewSalem());
		addTZToMap(tzMapping, timeZoneConstants.americaPanama());
		addTZToMap(tzMapping, timeZoneConstants.americaPangnirtung());
		addTZToMap(tzMapping, timeZoneConstants.americaParamaribo());
		addTZToMap(tzMapping, timeZoneConstants.americaPhoenix());
		addTZToMap(tzMapping, timeZoneConstants.americaPortauPrince());
		addTZToMap(tzMapping, timeZoneConstants.americaPortofSpain());
		addTZToMap(tzMapping, timeZoneConstants.americaPortoVelho());
		addTZToMap(tzMapping, timeZoneConstants.americaPuertoRico());
		addTZToMap(tzMapping, timeZoneConstants.americaRainyRiver());
		addTZToMap(tzMapping, timeZoneConstants.americaRankinInlet());
		addTZToMap(tzMapping, timeZoneConstants.americaRecife());
		addTZToMap(tzMapping, timeZoneConstants.americaRegina());
		addTZToMap(tzMapping, timeZoneConstants.americaRioBranco());
		addTZToMap(tzMapping, timeZoneConstants.americaSantiago());
		addTZToMap(tzMapping, timeZoneConstants.americaSantoDomingo());
		addTZToMap(tzMapping, timeZoneConstants.americaSaoPaulo());
		addTZToMap(tzMapping, timeZoneConstants.americaScoresbysund());
		addTZToMap(tzMapping, timeZoneConstants.americaShiprock());
		addTZToMap(tzMapping, timeZoneConstants.americaStJohns());
		addTZToMap(tzMapping, timeZoneConstants.americaStKitts());
		addTZToMap(tzMapping, timeZoneConstants.americaStLucia());
		addTZToMap(tzMapping, timeZoneConstants.americaStThomas());
		addTZToMap(tzMapping, timeZoneConstants.americaStVincent());
		addTZToMap(tzMapping, timeZoneConstants.americaSwiftCurrent());
		addTZToMap(tzMapping, timeZoneConstants.americaTegucigalpa());
		addTZToMap(tzMapping, timeZoneConstants.americaThule());
		addTZToMap(tzMapping, timeZoneConstants.americaThunderBay());
		addTZToMap(tzMapping, timeZoneConstants.americaTijuana());
		addTZToMap(tzMapping, timeZoneConstants.americaToronto());
		addTZToMap(tzMapping, timeZoneConstants.americaTortola());
		addTZToMap(tzMapping, timeZoneConstants.americaVancouver());
		addTZToMap(tzMapping, timeZoneConstants.americaWhitehorse());
		addTZToMap(tzMapping, timeZoneConstants.americaWinnipeg());
		addTZToMap(tzMapping, timeZoneConstants.americaYakutat());
		addTZToMap(tzMapping, timeZoneConstants.americaYellowknife());
		addTZToMap(tzMapping, timeZoneConstants.antarcticaCasey());
		addTZToMap(tzMapping, timeZoneConstants.antarcticaDavis());
		addTZToMap(tzMapping, timeZoneConstants.antarcticaDumontDUrville());
		addTZToMap(tzMapping, timeZoneConstants.antarcticaMawson());
		addTZToMap(tzMapping, timeZoneConstants.antarcticaMcMurdo());
		addTZToMap(tzMapping, timeZoneConstants.antarcticaPalmer());
		addTZToMap(tzMapping, timeZoneConstants.antarcticaRothera());
		addTZToMap(tzMapping, timeZoneConstants.antarcticaSyowa());
		addTZToMap(tzMapping, timeZoneConstants.antarcticaVostok());
		addTZToMap(tzMapping, timeZoneConstants.asiaAden());
		addTZToMap(tzMapping, timeZoneConstants.asiaAlmaty());
		addTZToMap(tzMapping, timeZoneConstants.asiaAmman());
		addTZToMap(tzMapping, timeZoneConstants.asiaAnadyr());
		addTZToMap(tzMapping, timeZoneConstants.asiaAqtau());
		addTZToMap(tzMapping, timeZoneConstants.asiaAqtobe());
		addTZToMap(tzMapping, timeZoneConstants.asiaAshgabat());
		addTZToMap(tzMapping, timeZoneConstants.asiaBaghdad());
		addTZToMap(tzMapping, timeZoneConstants.asiaBahrain());
		addTZToMap(tzMapping, timeZoneConstants.asiaBaku());
		addTZToMap(tzMapping, timeZoneConstants.asiaBangkok());
		addTZToMap(tzMapping, timeZoneConstants.asiaBeirut());
		addTZToMap(tzMapping, timeZoneConstants.asiaBishkek());
		addTZToMap(tzMapping, timeZoneConstants.asiaBrunei());
		addTZToMap(tzMapping, timeZoneConstants.asiaCalcutta());
		addTZToMap(tzMapping, timeZoneConstants.asiaChoibalsan());
		addTZToMap(tzMapping, timeZoneConstants.asiaChongqing());
		addTZToMap(tzMapping, timeZoneConstants.asiaColombo());
		addTZToMap(tzMapping, timeZoneConstants.asiaDamascus());
		addTZToMap(tzMapping, timeZoneConstants.asiaDhaka());
		addTZToMap(tzMapping, timeZoneConstants.asiaDili());
		addTZToMap(tzMapping, timeZoneConstants.asiaDubai());
		addTZToMap(tzMapping, timeZoneConstants.asiaDushanbe());
		addTZToMap(tzMapping, timeZoneConstants.asiaGaza());
		addTZToMap(tzMapping, timeZoneConstants.asiaHarbin());
		addTZToMap(tzMapping, timeZoneConstants.asiaHongKong());
		addTZToMap(tzMapping, timeZoneConstants.asiaHovd());
		addTZToMap(tzMapping, timeZoneConstants.asiaIrkutsk());
		addTZToMap(tzMapping, timeZoneConstants.asiaJakarta());
		addTZToMap(tzMapping, timeZoneConstants.asiaJayapura());
		addTZToMap(tzMapping, timeZoneConstants.asiaJerusalem());
		addTZToMap(tzMapping, timeZoneConstants.asiaKabul());
		addTZToMap(tzMapping, timeZoneConstants.asiaKamchatka());
		addTZToMap(tzMapping, timeZoneConstants.asiaKarachi());
		addTZToMap(tzMapping, timeZoneConstants.asiaKashgar());
		addTZToMap(tzMapping, timeZoneConstants.asiaKatmandu());
		addTZToMap(tzMapping, timeZoneConstants.asiaKrasnoyarsk());
		addTZToMap(tzMapping, timeZoneConstants.asiaKualaLumpur());
		addTZToMap(tzMapping, timeZoneConstants.asiaKuching());
		addTZToMap(tzMapping, timeZoneConstants.asiaKuwait());
		addTZToMap(tzMapping, timeZoneConstants.asiaMacau());
		addTZToMap(tzMapping, timeZoneConstants.asiaMagadan());
		addTZToMap(tzMapping, timeZoneConstants.asiaMakassar());
		addTZToMap(tzMapping, timeZoneConstants.asiaManila());
		addTZToMap(tzMapping, timeZoneConstants.asiaMuscat());
		addTZToMap(tzMapping, timeZoneConstants.asiaNicosia());
		addTZToMap(tzMapping, timeZoneConstants.asiaNovosibirsk());
		addTZToMap(tzMapping, timeZoneConstants.asiaOmsk());
		addTZToMap(tzMapping, timeZoneConstants.asiaOral());
		addTZToMap(tzMapping, timeZoneConstants.asiaPhnomPenh());
		addTZToMap(tzMapping, timeZoneConstants.asiaPontianak());
		addTZToMap(tzMapping, timeZoneConstants.asiaPyongyang());
		addTZToMap(tzMapping, timeZoneConstants.asiaQatar());
		addTZToMap(tzMapping, timeZoneConstants.asiaQyzylorda());
		addTZToMap(tzMapping, timeZoneConstants.asiaRangoon());
		addTZToMap(tzMapping, timeZoneConstants.asiaRiyadh());
		addTZToMap(tzMapping, timeZoneConstants.asiaSaigon());
		addTZToMap(tzMapping, timeZoneConstants.asiaSakhalin());
		addTZToMap(tzMapping, timeZoneConstants.asiaSamarkand());
		addTZToMap(tzMapping, timeZoneConstants.asiaSeoul());
		addTZToMap(tzMapping, timeZoneConstants.asiaShanghai());
		addTZToMap(tzMapping, timeZoneConstants.asiaSingapore());
		addTZToMap(tzMapping, timeZoneConstants.asiaTaipei());
		addTZToMap(tzMapping, timeZoneConstants.asiaTashkent());
		addTZToMap(tzMapping, timeZoneConstants.asiaTbilisi());
		addTZToMap(tzMapping, timeZoneConstants.asiaTehran());
		addTZToMap(tzMapping, timeZoneConstants.asiaThimphu());
		addTZToMap(tzMapping, timeZoneConstants.asiaTokyo());
		addTZToMap(tzMapping, timeZoneConstants.asiaUlaanbaatar());
		addTZToMap(tzMapping, timeZoneConstants.asiaUrumqi());
		addTZToMap(tzMapping, timeZoneConstants.asiaVientiane());
		addTZToMap(tzMapping, timeZoneConstants.asiaVladivostok());
		addTZToMap(tzMapping, timeZoneConstants.asiaYakutsk());
		addTZToMap(tzMapping, timeZoneConstants.asiaYekaterinburg());
		addTZToMap(tzMapping, timeZoneConstants.asiaYerevan());
		addTZToMap(tzMapping, timeZoneConstants.atlanticAzores());
		addTZToMap(tzMapping, timeZoneConstants.atlanticBermuda());
		addTZToMap(tzMapping, timeZoneConstants.atlanticCanary());
		addTZToMap(tzMapping, timeZoneConstants.atlanticCapeVerde());
		addTZToMap(tzMapping, timeZoneConstants.atlanticFaeroe());
		addTZToMap(tzMapping, timeZoneConstants.atlanticMadeira());
		addTZToMap(tzMapping, timeZoneConstants.atlanticReykjavik());
		addTZToMap(tzMapping, timeZoneConstants.atlanticSouthGeorgia());
		addTZToMap(tzMapping, timeZoneConstants.atlanticStanley());
		addTZToMap(tzMapping, timeZoneConstants.atlanticStHelena());
		addTZToMap(tzMapping, timeZoneConstants.australiaAdelaide());
		addTZToMap(tzMapping, timeZoneConstants.australiaBrisbane());
		addTZToMap(tzMapping, timeZoneConstants.australiaBrokenHill());
		addTZToMap(tzMapping, timeZoneConstants.australiaCurrie());
		addTZToMap(tzMapping, timeZoneConstants.australiaDarwin());
		addTZToMap(tzMapping, timeZoneConstants.australiaEucla());
		addTZToMap(tzMapping, timeZoneConstants.australiaHobart());
		addTZToMap(tzMapping, timeZoneConstants.australiaLindeman());
		addTZToMap(tzMapping, timeZoneConstants.australiaLordHowe());
		addTZToMap(tzMapping, timeZoneConstants.australiaMelbourne());
		addTZToMap(tzMapping, timeZoneConstants.australiaPerth());
		addTZToMap(tzMapping, timeZoneConstants.australiaSydney());
		addTZToMap(tzMapping, timeZoneConstants.europeAmsterdam());
		addTZToMap(tzMapping, timeZoneConstants.europeAndorra());
		addTZToMap(tzMapping, timeZoneConstants.europeAthens());
		addTZToMap(tzMapping, timeZoneConstants.europeBelgrade());
		addTZToMap(tzMapping, timeZoneConstants.europeBerlin());
		addTZToMap(tzMapping, timeZoneConstants.europeBratislava());
		addTZToMap(tzMapping, timeZoneConstants.europeBrussels());
		addTZToMap(tzMapping, timeZoneConstants.europeBucharest());
		addTZToMap(tzMapping, timeZoneConstants.europeBudapest());
		addTZToMap(tzMapping, timeZoneConstants.europeChisinau());
		addTZToMap(tzMapping, timeZoneConstants.europeCopenhagen());
		addTZToMap(tzMapping, timeZoneConstants.europeDublin());
		addTZToMap(tzMapping, timeZoneConstants.europeGibraltar());
		addTZToMap(tzMapping, timeZoneConstants.europeHelsinki());
		addTZToMap(tzMapping, timeZoneConstants.europeIstanbul());
		addTZToMap(tzMapping, timeZoneConstants.europeKaliningrad());
		addTZToMap(tzMapping, timeZoneConstants.europeKiev());
		addTZToMap(tzMapping, timeZoneConstants.europeLisbon());
		addTZToMap(tzMapping, timeZoneConstants.europeLjubljana());
		addTZToMap(tzMapping, timeZoneConstants.europeLondon());
		addTZToMap(tzMapping, timeZoneConstants.europeLuxembourg());
		addTZToMap(tzMapping, timeZoneConstants.europeMadrid());
		addTZToMap(tzMapping, timeZoneConstants.europeMalta());
		addTZToMap(tzMapping, timeZoneConstants.europeMinsk());
		addTZToMap(tzMapping, timeZoneConstants.europeMonaco());
		addTZToMap(tzMapping, timeZoneConstants.europeMoscow());
		addTZToMap(tzMapping, timeZoneConstants.europeOslo());
		addTZToMap(tzMapping, timeZoneConstants.europeParis());
		addTZToMap(tzMapping, timeZoneConstants.europePodgorica());
		addTZToMap(tzMapping, timeZoneConstants.europePrague());
		addTZToMap(tzMapping, timeZoneConstants.europeRiga());
		addTZToMap(tzMapping, timeZoneConstants.europeRome());
		addTZToMap(tzMapping, timeZoneConstants.europeSamara());
		addTZToMap(tzMapping, timeZoneConstants.europeSarajevo());
		addTZToMap(tzMapping, timeZoneConstants.europeSimferopol());
		addTZToMap(tzMapping, timeZoneConstants.europeSkopje());
		addTZToMap(tzMapping, timeZoneConstants.europeSofia());
		addTZToMap(tzMapping, timeZoneConstants.europeStockholm());
		addTZToMap(tzMapping, timeZoneConstants.europeTallinn());
		addTZToMap(tzMapping, timeZoneConstants.europeTirane());
		addTZToMap(tzMapping, timeZoneConstants.europeUzhgorod());
		addTZToMap(tzMapping, timeZoneConstants.europeVaduz());
		addTZToMap(tzMapping, timeZoneConstants.europeVienna());
		addTZToMap(tzMapping, timeZoneConstants.europeVilnius());
		addTZToMap(tzMapping, timeZoneConstants.europeVolgograd());
		addTZToMap(tzMapping, timeZoneConstants.europeWarsaw());
		addTZToMap(tzMapping, timeZoneConstants.europeZagreb());
		addTZToMap(tzMapping, timeZoneConstants.europeZaporozhye());
		addTZToMap(tzMapping, timeZoneConstants.europeZurich());
		addTZToMap(tzMapping, timeZoneConstants.indianAntananarivo());
		addTZToMap(tzMapping, timeZoneConstants.indianChagos());
		addTZToMap(tzMapping, timeZoneConstants.indianChristmas());
		addTZToMap(tzMapping, timeZoneConstants.indianCocos());
		addTZToMap(tzMapping, timeZoneConstants.indianComoro());
		addTZToMap(tzMapping, timeZoneConstants.indianKerguelen());
		addTZToMap(tzMapping, timeZoneConstants.indianMahe());
		addTZToMap(tzMapping, timeZoneConstants.indianMaldives());
		addTZToMap(tzMapping, timeZoneConstants.indianMauritius());
		addTZToMap(tzMapping, timeZoneConstants.indianMayotte());
		addTZToMap(tzMapping, timeZoneConstants.indianReunion());
		addTZToMap(tzMapping, timeZoneConstants.pacificApia());
		addTZToMap(tzMapping, timeZoneConstants.pacificAuckland());
		addTZToMap(tzMapping, timeZoneConstants.pacificChatham());
		addTZToMap(tzMapping, timeZoneConstants.pacificEaster());
		addTZToMap(tzMapping, timeZoneConstants.pacificEfate());
		addTZToMap(tzMapping, timeZoneConstants.pacificEnderbury());
		addTZToMap(tzMapping, timeZoneConstants.pacificFakaofo());
		addTZToMap(tzMapping, timeZoneConstants.pacificFiji());
		addTZToMap(tzMapping, timeZoneConstants.pacificFunafuti());
		addTZToMap(tzMapping, timeZoneConstants.pacificGalapagos());
		addTZToMap(tzMapping, timeZoneConstants.pacificGambier());
		addTZToMap(tzMapping, timeZoneConstants.pacificGuadalcanal());
		addTZToMap(tzMapping, timeZoneConstants.pacificGuam());
		addTZToMap(tzMapping, timeZoneConstants.pacificHonolulu());
		addTZToMap(tzMapping, timeZoneConstants.pacificJohnston());
		addTZToMap(tzMapping, timeZoneConstants.pacificKiritimati());
		addTZToMap(tzMapping, timeZoneConstants.pacificKosrae());
		addTZToMap(tzMapping, timeZoneConstants.pacificKwajalein());
		addTZToMap(tzMapping, timeZoneConstants.pacificMajuro());
		addTZToMap(tzMapping, timeZoneConstants.pacificMarquesas());
		addTZToMap(tzMapping, timeZoneConstants.pacificMidway());
		addTZToMap(tzMapping, timeZoneConstants.pacificNauru());
		addTZToMap(tzMapping, timeZoneConstants.pacificNiue());
		addTZToMap(tzMapping, timeZoneConstants.pacificNorfolk());
		addTZToMap(tzMapping, timeZoneConstants.pacificNoumea());
		addTZToMap(tzMapping, timeZoneConstants.pacificPagoPago());
		addTZToMap(tzMapping, timeZoneConstants.pacificPalau());
		addTZToMap(tzMapping, timeZoneConstants.pacificPitcairn());
		addTZToMap(tzMapping, timeZoneConstants.pacificPonape());
		addTZToMap(tzMapping, timeZoneConstants.pacificPortMoresby());
		addTZToMap(tzMapping, timeZoneConstants.pacificRarotonga());
		addTZToMap(tzMapping, timeZoneConstants.pacificSaipan());
		addTZToMap(tzMapping, timeZoneConstants.pacificTahiti());
		addTZToMap(tzMapping, timeZoneConstants.pacificTarawa());
		addTZToMap(tzMapping, timeZoneConstants.pacificTongatapu());
		addTZToMap(tzMapping, timeZoneConstants.pacificTruk());
		addTZToMap(tzMapping, timeZoneConstants.pacificWake());
		addTZToMap(tzMapping, timeZoneConstants.pacificWallis());
	}

	private static void addTZToMap(Map<String, TimeZone> map, String tzJSON) {
		TimeZone tz = TimeZone.createTimeZone(tzJSON);
		map.put(tz.getID(),tz);
	}
}
